version: '3.5'

services:
  worker:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew -q execute -PmainClass=io.temporal.samples.hello.HelloActivity"

